### ISSUE TITLE
Locking a semaphore fails across multiple servers

### ISSUE THREAD

**Issue by Geesu** [dv/redis-semaphore#28]
I have multiple servers that are hosting our rails application and for some reason locking a semaphore on one server doesn't propagate to the other.

Both are connected to the exact same redis server, and the object returned shows the same.  Example code:

https://gist.github.com/Geesu/defe63d00fbf4c880e84

Any ideas as to why the semaphore won't stay locked across multiple servers/processes connected to the same redis server?

Edit: In case you want to see Aperture.redis: https://gist.github.com/Geesu/0870fddc999d87612ec1

Edit 2: What's interesting is if I flush the redis server, it suddenly starts working as expected

**Comment by dv** [comment]
Great response, @jbielick is correct! Maybe this should be more clear in the documentation.
