### ISSUE TITLE
Available keys are not expired when expiration is set

### ISSUE THREAD

**Issue by skateinmars** [dv/redis-semaphore#32]
Following the change introduced in this pull request: https://github.com/dv/redis-semaphore/pull/24
The semaphore keys are created with the correct TTL in redis but when using BLPOP, the redis "available key" will be deleted and will lose its ttl. When the lock is released and the token added back to the list the key will exist again without its expiration set.
I think a simple expire could be set in the signal step to fix this?

**Comment by dv** [comment]
Good observation, thanks! @dany1468 fixed it, should end up in the next version.
