### ISSUE TITLE
Question: Lock across applications

### ISSUE THREAD

**Issue by NekoNova** [dv/redis-semaphore#41]
Hello,

I'm sorry if this comes across as a stupid questions, but we have a Sidekiq setup, and multiple Queue's as well as applications.
If they all point to the same Redis, and claim a lock on the same key, then this will block them all right?
Trying to look for a blocking solution that will work across multiple VM's.

**Comment by dv** [comment]
Hey NekoNova,

That's exactly right!

**Comment by NekoNova** [comment]
okay, cheers for the confirmation.
Concurrency issues are starting to get on my nerves, and trying to push forward the Redis Semaphore implementation to handle them across Sidekiq queues.
